### ISSUE TITLE
Unable to destroy an application -- raises an error

### ISSUE THREAD

**Issue by heathd** [alphagov/signonotron2#362]
Hi,

I tried to delete the `Errbit (Draft)` application on preview which is not needed any more, but got an error (see below). I think that the reason for this is that there's still an association to the permissions table from [Doorkeeper::Application](https://github.com/alphagov/signonotron2/blob/master/app/models/enhancements/application.rb#L6) but that table was dropped in https://github.com/alphagov/signonotron2/pull/328

```
irb(main):006:0> ed = Doorkeeper::Application.where("name like '%errbit%'").last
=> #<Doorkeeper::Application id: 39, name: "Errbit (Draft)", uid: ".......", secret: "...", redirect_uri: "https://errbit.draft.preview.publishing.service.gov...", created_at: "2015-05-07 14:23:11", updated_at: "2015-05-07 14:23:11", home_uri: "https://errbit.draft.preview.publishing.service.gov...", description: "Draft stack Errbit", supports_push_updates: true>
irb(main):007:0> ed.destroy
Mysql2::Error: Table 'signon_production.permissions' doesn't exist: SHOW FULL FIELDS FROM `permissions`
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'signon_production.permissions' doesn't exist: SHOW FULL FIELDS FROM `permissions`
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:301:in `execute_and_free'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:462:in `columns'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:114:in `block in prepare_default_proc'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:56:in `yield'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:118:in `block in prepare_default_proc'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:67:in `yield'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/schema_cache.rb:67:in `columns_hash'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/associations/association_scope.rb:25:in `column_for'
... 14 levels...
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:292:in `destroy'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:265:in `block in destroy'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:330:in `block in with_transaction_returning_status'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:209:in `transaction'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:327:in `with_transaction_returning_status'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:265:in `destroy'
	from (irb):7
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/commands/console.rb:90:in `start'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/commands/console.rb:9:in `start'
	from /data/apps/signon/shared/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
```

**Comment by tekin** [comment]
The `permissions` table was dropped in the pull request linked to above, but the model file still exists and also the `has_many :permissions` association is still there in `::Doorkeeper::Application`.
